apiVersion: v1
kind: Service
metadata:
  name: userver-demo-service
  namespace: pavelbezpravel
spec:
  selector:
    app: my-awesome-app
  ports:
    - port: 8091
      targetPort: 8091
  type: ClusterIP
