apiVersion: apps/v1
kind: Deployment
metadata:
  name: userver-demo-deployment
  namespace: pavelbezpravel
  labels:
    app: my-awesome-app
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-awesome-app
  template:
    metadata:
      labels:
        app: my-awesome-app
    spec:
      containers:
        - name: app
          image: pavelbezpravel/userver-demo:0.1.0
          ports:
            - containerPort: 8091
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
