apiVersion: v1
kind: Pod
metadata:
  name: userver-demo
  namespace: pavelbezpravel
  labels:
    app: grpc-server
    env: prod
spec:
  containers:
    - name: app
      image: pavelbezpravel/userver-demo:0.1.0
      ports:
        - name: grpc-insecure
          containerPort: 8091
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: userver-demo-service
  namespace: pavelbezpravel
spec:
  selector:
    app: grpc-server
  ports:
    - name: grpc-insecure
      port: 8091
      targetPort: 8091
