apiVersion: v1
kind: ReplicationController
metadata:
  name: userver-demo-rc
  namespace: pavelbezpravel
spec:
  replicas: 3
  selector:
    app: my-awesome-app
  template:
    metadata:
      name: userver-demo-app
      labels:
        app: my-awesome-app
    spec:
      containers:
        - name: app
          image: pavelbezpravel/userver-demo:0.1.0
          ports:
            - containerPort: 8091
